function attr = dicom_create_attr
%DICOM_CREATE_ATTR  Create a structure to contain an attribute.
%   ATTR = DICOM_CREATE_ATTR create a structure ATTR to contain an
%   attribute's metadata.  The fields are filled with empty values.

%   Copyright 1993-2005 The MathWorks, Inc.
%   $Revision: 1.1.6.2 $  $Date: 2005/11/15 01:04:14 $

attr = struct('Name', '', ...
              'Group', [], ...
              'Element', [], ...
              'VR', '', ...
              'VM', [], ...
              'Length', []);
